console.log(process.version);
console.log(process.arch);
// require("dotenv");
const secretId = process.env.SECRET_ID;
const secretCode = process.env.SECRET_CODE;

console.log(SECRET_ID);
console.log(secretCode);

proc = `
process {
  version: 'v20.15.0',
  versions: {
    node: '20.15.0',
    acorn: '8.11.3',
    ada: '2.7.8',
    ares: '1.28.1',
    base64: '0.5.2',
    brotli: '1.1.0',
    cjs_module_lexer: '1.2.2',
    cldr: '45.0',
    icu: '75.1',
    llhttp: '8.1.2',
    modules: '115',
    napi: '9',
    nghttp2: '1.61.0',
    nghttp3: '0.7.0',
    ngtcp2: '1.1.0',
    openssl: '3.0.13+quic',
    simdutf: '5.2.8',
    tz: '2024a',
    undici: '6.13.0',
    unicode: '15.1',
    uv: '1.46.0',
    uvwasi: '0.0.21',
    v8: '11.3.244.8-node.23',
    zlib: '1.3.0.1-motley-7d77fb7'
  },
  arch: 'x64',
  platform: 'win32',
  release: {
    name: 'node',
    lts: 'Iron',
    sourceUrl: 'https://nodejs.org/download/release/v20.15.0/node-v20.15.0.tar.gz',
    headersUrl: 'https://nodejs.org/download/release/v20.15.0/node-v20.15.0-headers.tar.gz',
    libUrl: 'https://nodejs.org/download/release/v20.15.0/win-x64/node.lib'       
  },
  _rawDebug: [Function: _rawDebug],
  moduleLoadList: [
    'Internal Binding builtins',
    'Internal Binding module_wrap',
    'Internal Binding errors',
    'NativeModule internal/assert',
    'Internal Binding util',
    'NativeModule internal/errors',
    'Internal Binding config',
    'Internal Binding timers',
    'Internal Binding async_wrap',
    'Internal Binding task_queue',
    'Internal Binding symbols',
    'NativeModule internal/async_hooks',
    'Internal Binding constants',
    'Internal Binding types',
    'Internal Binding options',
    'NativeModule internal/options',
    'Internal Binding string_decoder',
    'NativeModule internal/util',
    'NativeModule internal/util/types',
    'NativeModule internal/validators',
    'NativeModule internal/linkedlist',
    'NativeModule internal/priority_queue',
    'Internal Binding icu',
    'NativeModule internal/util/inspect',
    'NativeModule internal/util/debuglog',
    'NativeModule internal/timers',
    'NativeModule internal/events/abort_listener',
    'NativeModule events',
    'Internal Binding buffer',
    'NativeModule internal/buffer',
    'NativeModule buffer',
    'Internal Binding messaging',
    'NativeModule internal/worker/js_transferable',
    'Internal Binding permission',
    'NativeModule internal/constants',
    'NativeModule path',
    'NativeModule internal/process/permission',
    'NativeModule internal/querystring',
    'NativeModule querystring',
    'Internal Binding url',
    'NativeModule internal/url',
    'Internal Binding encoding_binding',
    'NativeModule internal/fs/utils',
    'Internal Binding process_methods',
    'NativeModule internal/process/per_thread',
    'Internal Binding credentials',
    'NativeModule internal/process/promises',
    'NativeModule internal/fixed_queue',
    'NativeModule async_hooks',
    'NativeModule internal/process/task_queues',
    'NativeModule timers',
    'Internal Binding trace_events',
    'Internal Binding contextify',
    'NativeModule internal/vm',
    'NativeModule internal/process/execution',
    'NativeModule internal/process/warning',
    'NativeModule internal/source_map/source_map_cache',
    'NativeModule util',
    'NativeModule internal/console/constructor',
    'NativeModule internal/console/global',
    'NativeModule internal/util/inspector',
    'Internal Binding inspector',
    'NativeModule internal/webidl',
    'Internal Binding performance',
    'NativeModule internal/perf/utils',
    'NativeModule internal/event_target',
    'Internal Binding blob',
    'Internal Binding wasm_web_api',
    'Internal Binding mksnapshot',
    'NativeModule internal/v8/startup_snapshot',
    'NativeModule internal/process/signal',
    'Internal Binding fs',
    'NativeModule internal/encoding',
    'NativeModule internal/webstreams/util',
    'NativeModule internal/webstreams/queuingstrategies',
    'NativeModule internal/blob',
    'NativeModule fs',
    'NativeModule internal/idna',
    'NativeModule url',
    'NativeModule internal/modules/helpers',
    'NativeModule internal/modules/package_json_reader',
    'NativeModule internal/modules/cjs/loader',
    'NativeModule internal/process/pre_execution',
    'NativeModule internal/modules/esm/utils',
    'NativeModule internal/inspector_async_hook',
    'Internal Binding worker',
    'NativeModule internal/modules/run_main',
    'NativeModule internal/net',
    'NativeModule internal/dns/utils',
    'NativeModule internal/modules/esm/loader',
    'NativeModule internal/modules/esm/assert',
    'NativeModule internal/modules/esm/module_map',
    'NativeModule internal/modules/esm/translators',
    'NativeModule internal/abort_controller',
    'NativeModule internal/streams/utils',
    'NativeModule internal/streams/end-of-stream',
    'NativeModule internal/streams/destroy',
    'NativeModule internal/streams/legacy',
    'NativeModule internal/streams/add-abort-signal',
    'NativeModule internal/streams/state',
    ... 56 more items
  ],
  binding: [Function: binding],
  _linkedBinding: [Function: _linkedBinding],
  _events: [Object: null prototype] {
    newListener: [
      [Function (anonymous)],
      [Function: startListeningIfSignal],
      [Function (anonymous)]
    ],
    removeListener: [
      [Function (anonymous)],
      [Function: stopListeningIfSignal],
      [Function (anonymous)]
    ],
    warning: [Function: onWarning],
    SIGWINCH: [
      [Function: refreshStdoutOnSigWinch],
      [Function: refreshStderrOnSigWinch]
    ]
  },
  _eventsCount: 4,
  _maxListeners: undefined,
  domain: [Getter/Setter],
  _exiting: [Getter/Setter],
  exitCode: [Getter/Setter],
  config: {
    target_defaults: {
      cflags: [],
      default_configuration: 'Release',
      defines: [Array],
      include_dirs: [],
      libraries: []
    },
    variables: {
      asan: 0,
      coverage: false,
      dcheck_always_on: 0,
      debug_nghttp2: false,
      debug_node: false,
      enable_lto: false,
      enable_pgo_generate: false,
      enable_pgo_use: false,
      error_on_warn: false,
      force_dynamic_crt: 0,
      host_arch: 'x64',
      icu_data_in: '..\\..\\deps\\icu-tmp\\icudt75l.dat',
      icu_endianness: 'l',
      icu_gyp_path: 'tools/icu/icu-generic.gyp',
      icu_path: 'deps/icu-small',
      icu_small: false,
      icu_ver_major: '75',
      is_debug: 0,
      libdir: 'lib',
      llvm_version: '0.0',
      napi_build_version: '9',
      nasm_version: '2.16',
      node_builtin_shareable_builtins: [Array],
      node_byteorder: 'little',
      node_debug_lib: false,
      node_enable_d8: false,
      node_enable_v8_vtunejit: false,
      node_fipsinstall: false,
      node_install_corepack: true,
      node_install_npm: true,
      node_library_files: [Array],
      node_module_version: 115,
      node_no_browser_globals: false,
      node_prefix: '\\usr\\local',
      node_release_urlbase: 'https://nodejs.org/download/release/',
      node_shared: false,
      node_shared_ada: false,
      node_shared_brotli: false,
      node_shared_cares: false,
      node_shared_http_parser: false,
      node_shared_libuv: false,
      node_shared_nghttp2: false,
      node_shared_nghttp3: false,
      node_shared_ngtcp2: false,
      node_shared_openssl: false,
      node_shared_simdjson: false,
      node_shared_simdutf: false,
      node_shared_zlib: false,
      node_tag: '',
      node_target_type: 'executable',
      node_use_bundled_v8: true,
      node_use_node_code_cache: true,
      node_use_node_snapshot: true,
      node_use_openssl: true,
      node_use_v8_platform: true,
      node_with_ltcg: true,
      node_without_node_options: false,
      node_write_snapshot_as_array_literals: true,
      openssl_is_fips: false,
      openssl_quic: true,
      ossfuzz: false,
      shlib_suffix: 'so.115',
      single_executable_application: true,
      target_arch: 'x64',
      ubsan: 0,
      use_prefix_to_find_headers: false,
      v8_enable_31bit_smis_on_64bit_arch: 0,
      v8_enable_extensible_ro_snapshot: 0,
      v8_enable_gdbjit: 0,
      v8_enable_hugepage: 0,
      v8_enable_i18n_support: 1,
      v8_enable_inspector: 1,
      v8_enable_javascript_promise_hooks: 1,
      v8_enable_lite_mode: 0,
      v8_enable_maglev: 0,
      v8_enable_object_print: 1,
      v8_enable_pointer_compression: 0,
      v8_enable_shared_ro_heap: 1,
      v8_enable_short_builtin_calls: 1,
      v8_enable_v8_checks: 0,
      v8_enable_webassembly: 1,
      v8_no_strict_aliasing: 1,
      v8_optimized_debug: 1,
      v8_promise_internal_field_count: 1,
      v8_random_seed: 0,
      v8_trace_maps: 0,
      v8_use_siphash: 1,
      want_separate_host_toolset: 0
    }
  },
  dlopen: [Function: dlopen],
  uptime: [Function: uptime],
  _getActiveRequests: [Function: _getActiveRequests],
  _getActiveHandles: [Function: _getActiveHandles],
  getActiveResourcesInfo: [Function: getActiveResourcesInfo],
  reallyExit: [Function: reallyExit],
  _kill: [Function: _kill],
  loadEnvFile: [Function: loadEnvFile],
  cpuUsage: [Function: cpuUsage],
  resourceUsage: [Function: resourceUsage],
  memoryUsage: [Function: memoryUsage] { rss: [Function: rss] },
  constrainedMemory: [Function: constrainedMemory],
  availableMemory: [Function: availableMemory],
  kill: [Function: kill],
  exit: [Function: exit],
  hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
  openStdin: [Function (anonymous)],
  allowedNodeEnvironmentFlags: [Getter/Setter],
  assert: [Function: deprecated],
  features: {
    inspector: true,
    debug: false,
    uv: true,
    ipv6: true,
    tls_alpn: true,
    tls_sni: true,
    tls_ocsp: true,
    tls: true,
    cached_builtins: [Getter]
  },
  _fatalException: [Function (anonymous)],
  setUncaughtExceptionCaptureCallback: [Function (anonymous)],
  hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
  emitWarning: [Function: emitWarning],
  nextTick: [Function: nextTick],
  _tickCallback: [Function: runNextTicks],
  sourceMapsEnabled: [Getter],
  setSourceMapsEnabled: [Function: setSourceMapsEnabled],
  _debugProcess: [Function: _debugProcess],
  _debugEnd: [Function: _debugEnd],
  _startProfilerIdleNotifier: [Function (anonymous)],
  _stopProfilerIdleNotifier: [Function (anonymous)],
  stdout: [Getter],
  stdin: [Getter],
  stderr: [Getter],
  abort: [Function: abort],
  umask: [Function: wrappedUmask],
  chdir: [Function (anonymous)],
  cwd: [Function: wrappedCwd],
  env: {
    ALLUSERSPROFILE: 'C:\\ProgramData',
    APPDATA: 'C:\\Users\\USER\\AppData\\Roaming',
    CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_2592_KMUOORKFOHKBEUTF',     
    CHROME_EXECUTABLE: 'C:\\Scoop\\apps\\googlechrome\\current\\chrome.exe',      
    CommonProgramFiles: 'C:\\Program Files\\Common Files',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'DESKTOP-1OSIV89',
    ComSpec: 'C:\\Windows\\system32\\cmd.exe',
    configsetroot: 'C:\\Windows\\ConfigSetRoot',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
    FPS_BROWSER_USER_PROFILE_STRING: 'Default',
    GIT_INSTALL_ROOT: 'C:\\Scoop\\apps\\git\\current',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\USER',
    IGCCSVC_DB: 'AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAAnNn5o9BvE6GmsvkUEl4fQQAAAACAAAAAAAQZgAAAAEAACAAAAA1QghJve704tLw0POLKKDDFQ/qwINFttvGt1rfe/xaUgAAAAAOgAAAAAIAACAAAAAD0zKnGuFrumw/t/W88DbZBOl4ETKEAtsZiwyaG8Z2zGAAAADUg0lLOQVFHd9BW7IhX2C9eOrnjhPtqejGeZKFXrPLtQBjINnWfnTWyT65/IaY1VkPOngh3ARB0f2+n8rkcsWJB6aZ9/z4jdQn1OeHqta5V5f+S/NGvFYBgU4sGitj4w1AAAAAcwyqFvFAPACG5VmmNoW3c6ftqaa9caSDd/aHRgAUPlRAyUWn2eGIx9Yr09Q4DB0emwwFYX7oXU4JCq54HFNiyg==',
    LOCALAPPDATA: 'C:\\Users\\USER\\AppData\\Local',
    LOGONSERVER: '\\\\DESKTOP-1OSIV89',
    NUMBER_OF_PROCESSORS: '12',
    OneDrive: 'C:\\Users\\USER\\OneDrive',
    ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
    OS: 'Windows_NT',
    Path: 'C:\\Scoop\\apps\\anaconda3\\current\\Scripts;C:\\Scoop\\apps\\anaconda3\\current;C:\\python\\Scripts\\;C:\\python\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\Scoop\\apps\\anaconda3\\current\\App\\Scripts;C:\\Scoop\\apps\\vscode\\current\\bin;C:\\Scoop\\apps\\nodejs-lts\\current\\bin;C:\\Scoop\\apps\\nodejs-lts\\current;C:\\Scoop\\shims;C:\\Users\\USER\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\USER\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Scoop\\apps\\anaconda3\\current\\App\\Scripts;',
    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 151 Stepping 5, GenuineIntel',
    PROCESSOR_LEVEL: '6',
    PROCESSOR_REVISION: '9705',
    ProgramData: 'C:\\ProgramData',
    ProgramFiles: 'C:\\Program Files',
    'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    PSModulePath: 'C:\\Users\\USER\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files\\Intel\\Wired Networking\\',
    PUBLIC: 'C:\\Users\\Public',
    Scoop: 'C:\\Scoop',
    SESSIONNAME: 'Console',
    SystemDrive: 'C:',
    SystemRoot: 'C:\\Windows',
    TEMP: 'C:\\Users\\USER\\AppData\\Local\\Temp',
    TMP: 'C:\\Users\\USER\\AppData\\Local\\Temp',
    USERDOMAIN: 'DESKTOP-1OSIV89',
    USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-1OSIV89',
    USERNAME: 'USER',
    USERPROFILE: 'C:\\Users\\USER',
    VBOX_MSI_INSTALL_PATH: 'C:\\Program Files\\Oracle\\VirtualBox\\',
    windir: 'C:\\Windows',
    ZES_ENABLE_SYSMAN: '1',
    TERM_PROGRAM: 'vscode',
    TERM_PROGRAM_VERSION: '1.91.1',
    LANG: 'en_US.UTF-8',
    COLORTERM: 'truecolor',
    GIT_ASKPASS: 'c:\\Users\\USER\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
    VSCODE_GIT_ASKPASS_NODE: 'C:\\Users\\USER\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
    VSCODE_GIT_ASKPASS_EXTRA_ARGS: '',
    VSCODE_GIT_ASKPASS_MAIN: 'c:\\Users\\USER\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
    VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-b58b39d78e-sock',
    VSCODE_INJECTION: '1'
  },
  title: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',        
  argv: [ 'C:\\Scoop\\apps\\nodejs-lts\\current\\node.exe' ],
  execArgv: [],
  pid: 14196,
  ppid: 2360,
  execPath: 'C:\\Scoop\\apps\\nodejs-lts\\current\\node.exe',
  debugPort: 9229,
  argv0: 'C:\\Scoop\\apps\\nodejs-lts\\current\\node.exe',
  _preload_modules: [],
  report: [Getter],
  [Symbol(shapeMode)]: false,
  [Symbol(kCapture)]: false
}
`;
